### ISSUE TITLE
Complex Pipeline Failure - ValueError

### ISSUE THREAD

**Issue by cross12tamu** [debbiemarkslab/EVcouplings#229] opened 2020-03-19 17:23 UTC
This is somewhat related to Issue #215 

I am running a complex pipeline and during the later steps, it hangs on the attached issue.
![evcouplings_error](https://user-images.githubusercontent.com/26947059/77095419-dcb7aa80-69db-11ea-8369-6dbadbd667ac.png)

Let me know if there's anything else I need to provide for y'all.

Of note, I also did the (couple line) changes [seen here](https://github.com/debbiemarkslab/EVcouplings/pull/217/commits/9e6c0e6b729a42468dd7b5219a66a68bf0ef90dc)

Thanks!

( For other jobs, I am also getting errors related to #213 , in which I will bump )

**Comment by thomashopf** [comment] 2020-03-20 14:36
@cross12tamu Could you please upload the entire pipeline output folder including config files somewhere? Then we can have a more detailed look at the issue

**Comment by thomashopf** [comment] 2020-03-20 14:37
Looks like this may be the same issue as #222

**Comment by aggreen** [comment] 2020-03-20 17:40
@thomashopf agree this is the same issue

**Comment by cross12tamu** [comment] 2020-03-27 15:12
Hey yall,

Is there a good way to send the entire output and config here on github? I can compress and email as well.

**Comment by thomashopf** [comment] 2020-03-27 20:13
Any link where we can download the files is fine (not aware of large uploads being possible at github)

**Comment by cross12tamu** [comment] 2020-03-27 21:18
[Here a google drive link](https://drive.google.com/drive/folders/1v893Nm4sRMx5OBCXbhEaUYWrd9vHCZxJ?usp=sharing), let me know if it does not work.

**Comment by thomashopf** [comment] 2020-03-28 09:59
Thanks, this confirms we indeed have a duplicate of #222 here.

Until we have a fix implemented, in the "compare" section of you config, please change
``` 
plot_probability_cutoffs: [0.90, 0.99]
```

to

``` 
plot_probability_cutoffs: []
```

which will avoid running into the problematic code. 

Please let us know in case this still doesn't fix it for you temporarily, closing this issue in favor of #222 for now.

**Closed by thomashopf** 2020-03-28 09:59 UTC
