### ISSUE TITLE
Evcouplings_dbupdate ResourceError

### ISSUE THREAD

**Issue by JodC58972** [debbiemarkslab/EVcouplings#278] opened 2022-07-13 16:19 UTC
Running evcouplings_dbupdate -v -s ./SIFT/ -d ./Uniprot/  and getting this error: 

`line 105, in fetch_uniprot_mapping

    raise ResourceError( evcouplings.utils.system.ResourceError: Invalid status code (405) for URL: https://www.uniprot.org/mapping/`

Is anyone else getting this error? Is there a workaround? What is the correct URL?

**Comment by chiggsk** [comment] 2022-07-13 16:55
Hi, yes I can confirm I am also receiving this error, would love to hear any thoughts on resolving it!

**Comment by thomashopf** [comment] 2022-07-14 09:27
Looks like there were some changes to the UniProt REST API we are using to fetch sequences for all PDB entries.

I'll look into what it will take to update this, shouldn't be too large of a change hopefully.

We can supply some older versions of the file so you can still use that part of EVcouplings.

**Comment by JodC58972** [comment] 2022-07-18 15:15
Thanks so much. I contacted EVcouplings here: support@evcouplings.org.
I was able to get a help and a UniProt file thanks so much

**Comment by thomashopf** [comment] 2022-08-09 08:51
The issue has been fixed and is already part of the develop branch... we will push a new release to pypi shortly

**Comment by Yogesh1-11** [comment] 2023-03-15 04:00
hi i am getting error even  with development code. Is this the write way to download databases for the first time?

administrator@administrator-HP-Z6-G4-Workstation:~$ evcouplings_dbupdate /evc_database/sifts/ -d /evc_database/uniprot/ -v 
Updating SIFTS
Traceback (most recent call last):
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 1563, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 1584, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 2405, in __init__
    self.init()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 2415, in init
    self.ftp.login(self.user, self.passwd)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 412, in login
    resp = self.sendcmd('USER ' + user)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 244, in getresp
    resp = self.getmultiline()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 230, in getmultiline
    line = self.getline()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 218, in getline
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/anaconda3/envs/evc/bin/evcouplings_dbupdate", line 8, in <module>
    sys.exit(app())
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/evcouplings/utils/update_database.py", line 189, in app
    run(**kwargs)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/evcouplings/utils/update_database.py", line 131, in run
    s_new = SIFTS(sifts.format(year=year, month=month, day=day, extension="csv"))
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/evcouplings/compare/sifts.py", line 339, in __init__
    self._create_mapping_table(sifts_table_file)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/evcouplings/compare/sifts.py", line 405, in _create_mapping_table
    get_urllib(SIFTS_URL, temp_download_file)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/site-packages/evcouplings/utils/system.py", line 300, in get_urllib
    with urllib.request.urlopen(url) as r, open(output_path, 'wb') as f:
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 1581, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 1563, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 1584, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 2405, in __init__
    self.init()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/urllib/request.py", line 2415, in init
    self.ftp.login(self.user, self.passwd)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 412, in login
    resp = self.sendcmd('USER ' + user)
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 244, in getresp
    resp = self.getmultiline()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 230, in getmultiline
    line = self.getline()
  File "/home/administrator/anaconda3/envs/evc/lib/python3.9/ftplib.py", line 218, in getline
    raise EOFError
urllib.error.URLError: <urlopen error ftp error: EOFError()>

**Closed as completed** 2023-05-10 16:26 UTC
Labels: bug
