### ISSUE TITLE
Error running couplings for RNAs / unique alphabets

### ISSUE THREAD

**Issue by nrollins-Ag** [debbiemarkslab/EVcouplings#237] opened 2020-04-26 21:10 UTC
(1 not an error, but quality of life) When running couplings for an RNA alignment- it is necessary to specify "alphabet: -AUGC". Would be good to make this automatically defined
(2 an error) again when running couplings for an RNA alignment- EVzoom fails and crashes the pipeline. EVzoom is trying to pass non-RNA characters to the model

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 456, in execute_wrapped
    outcfg = execute(**config)
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 176, in execute
    outcfg = runner(**incfg)
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 801, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 310, in standard
    generate_line_plot=is_single_segment
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/couplings/protocol.py", line 742, in _postprocess_inference
    evzoom_json(model) + "\n"
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/visualize/parameters.py", line 174, in evzoom_json
    map_, logo, matrix = evzoom_data(model, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/visualize/parameters.py", line 75, in evzoom_data
    model.alphabet_map[c] for c in reorder
  File "/anaconda3/lib/python3.7/site-packages/evcouplings/visualize/parameters.py", line 75, in <listcomp>
    model.alphabet_map[c] for c in reorder
KeyError: 'K'

**Comment by thomashopf** [comment] 2020-04-27 19:25
(1) You can use "rna" as a shortcut - will think about having an "auto" mode that detects from input

(2) Duplicate of #196 - @jonnyfrazer I seem to remember you patched the fix into your copy of the pipeline, did that work?

**Comment by thomashopf** [comment] 2020-06-20 15:45
Re #196 - the fix I originally proposed in this issue is now in the fix/mysql_and_various_fixes branch and will get merged into the develop branch soon

**Comment by thomashopf** [comment] 2020-06-20 15:47
Closing this issue now in favor of #196

**Closed by thomashopf** 2020-06-20 15:47 UTC
Labels: bug

**Comment by thomashopf** [comment] 2020-07-24 07:52
Fixed by https://github.com/debbiemarkslab/EVcouplings/commit/5332e897ebc0528aa3cf63f8f962ff2254de84a5
