### ISSUE TITLE
Problems on reproducing paper results

### ISSUE THREAD

**Issue by bariskalem** [debbiemarkslab/EVcouplings#221] opened 2019-07-16 08:16 UTC
Hello,

We have downloaded the supplementary result file. (for the paper: [Sequence co-evolution gives 3D contacts and structures of protein complexes (2014](http://evfold.org/evfold-web/datasets.do)) )

And, we tried to reproduce the first result which is FRDA_ECOLI with FRDB_ECOLI using the default values on the webserver. However, we did not reproduce the results that are given in the supplementary file. For example, we do not get any inter-EC over 0.8, but the supplementary says there should be "2". 

How can we adjust the parameters so we can get the same results? What are the parameters that need adjusting?
Also we tried the webserver with our own proteins which are known to interact but we never get any score even close to the threshold value of 0.8. Is there some documentation of how to use the webserver properly?

Best regards

**Comment by aggreen** [comment] 2019-07-18 14:13
Hello,

There are multiple differences between the webserver default parameter
values and the values used in the 2014 paper. They are as follows:

1. The webserver defaults to using best hit based concatenation method,
whereas the 2014 paper used a genome distance-based concatenation. If you
change the "concatenate protocol" parameter to "Genome distance" and the
"database" parameter for both alignments to Uniprot, I think that this will
lead to good results.

2. The uniprot sequence databases have increased in size since the 2014
paper. If you want to exactly reproduce the results, you will have to use
the old sequence database.

3. The EVcomplex scoring function is no longer the default scoring method
for complexes. If you want to use this scoring method, you will have to
download this python package and use the evcomplex scoring method for your
run.

I hope that you find this helpful. I will close this issue on github, but
please don't hesitate to contact support@evcouplings.org with further
questions about your run.

Anna

**Closed** 2019-07-18 14:13 UTC
Labels: question, wontfix
