### ISSUE TITLE
evcouplings_runcfg uses #!/usr/bin/python3 instead of #!/usr/bin/env python

### ISSUE THREAD

**Issue by PeterARBork** [debbiemarkslab/EVcouplings#101] opened 2018-01-15 13:35 UTC
... And consequently fails to run, when the rest of EVcouplings is being used from a virtual environment.

Edit: This version is from a fresh installation today using
pip install evcouplings

Switching the first line between the two options in the title of this issue, I can get the following error due to python3.4 instead of my virtual environment's 3.6 being used, or a normal execution:

```
(venv_EVCouplings) /../EVcouplings$ evcouplings_runcfg
Traceback (most recent call last):
  File "/usr/local/bin/evcouplings_runcfg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python' distribution was not found and is required by mmtf-python
```

**Comment by sacdallago** [comment] 2018-01-15 14:51
@PeterARBork wonderful catch!

@b-schubert how do you feel about reviewing and changing this if indeed unintended? Just assigning you in case, but feel free to reassign :)

**Comment by b-schubert** [comment] 2018-01-15 17:47
Hey @PeterARBork,
thanks for the feedback! 

@sacdallago 
The shebang is autogenerated by setup tools, so its not a super easy fix. I'll see what I can do....

**Comment by b-schubert** [comment] 2018-01-15 18:08
See PR #103

**Comment by thomashopf** [comment] 2018-01-15 19:13
Thanks for reporting and submitting the PR... my minor issue is that it kills Windows usage (not that the pipeline has ever been tested under Windows)... is there any anticipation if/when this will be fixed in setuptools?

**Comment by b-schubert** [comment] 2018-01-15 19:31
The Issue is open since Feb 2016.... So probably no easy fix in sight or very low priority....

**Comment by thomashopf** [comment] 2018-01-16 07:03
Hmm after reading that issue I am very confused, since it suggests that the actual interpreter for that virtualenv should get substituted (hence the complaints about too long paths getting truncated). So I wonder if there is an issue with @PeterARBork‘s virtualenv setup here rather than setuptools?

**Comment by PeterARBork** [comment] 2018-01-16 08:54
@thomashopf, it might well be my setup that has an issue. Where are the complaints about too long paths getting truncated?

**Comment by thomashopf** [comment] 2018-01-16 18:07
@PeterARBork They are found here: https://github.com/pypa/setuptools/issues/494

**Comment by PeterARBork** [comment] 2018-01-23 08:37
@thomashopf, can I do something to help you close this issue?

**Comment by b-schubert** [comment] 2018-01-23 15:35
Im still a bit confused....Setuptools sets the path to the python binary that was used to compile the package. Your call and the stack trace however indicates that you have compiled EVcouplings with your system python version, not with the python binary of venv_EVCouplings. Is that correct?

**Comment by PeterARBork** [comment] 2018-01-23 23:00
@b-schubert, I did the following on 14.04.1-Ubuntu:
1. /../miniconda3/bin/python3.6 -m venv venv_EVCouplings
2. activate environment,
3. pip install evcouplings
4. Try running command shown in first stacktrace above, and discover that the shebang line in the evcouplings_runcfg is pointing at system-wide installation. Edit the line etc. as shown above.

My system-wide python installation is version 3.4 and the errors I get from running outside of the virtual environment are noticeably different than the "right" errors.

I do not know why the shebang in the evcouplings_runcfg file pointed at system-wide python installation instead of the virtual environment from which I called pip install. I later uninstalled and re-installed bokeh to solve another issue using the same virtual environment and same pip and when I change the shebang line to ask for current environment's binary the problem solves, so I think the pip belonged to the right virtual environment.

The first line in the stacktrace shows that the virtual environment is activated, with '(venv_EVCouplings)' ahead of the prompt. Later in the stack-trace, the system-wide python 3.4 binaries have been used, which seems like a paradox. The shebang in evcouplings_runcfg was
#!/usr/bin/python3
and this explains the paradox. Even though I'm calling the script inside a virtual environment, the script will still use the shebang line to get the system-wide python binary in /usr/bin/python3 instead of the virtual environment binary located somewhere else. When I change the shebang to 
#!/usr/bin/env python
then the script correctly uses the virtual environment's python 3.6 binary and all is well.

My problem is resolved via changing the shebang line, but I'm happy to report further diagnostics as you need them.

**Comment by sacdallago** [comment] 2018-03-24 14:13
Anything to do here?

**Comment by b-schubert** [comment] 2018-03-24 14:26
there is no existing solution that works for all systems. It is an issue on setuptools site that has been known since 2015.

**Comment by sacdallago** [comment] 2018-03-24 14:28
Ok, wontfix and closing

**Closed by sacdallago** 2018-03-24 14:28 UTC
Labels: bug, wontfix
