### ISSUE TITLE
Make compatible with PSIPRED v4

### ISSUE THREAD

**Issue by cross12tamu** [debbiemarkslab/EVcouplings#230] opened 2020-03-27 15:20 UTC
Hey, I hope this finds yall well and in good spirits!

I'm having some issues troubleshooting regarding the fold step of the monomer pipeline.

The output of my error is as follows:

``` python
Traceback (most recent call last):
  File "execute-pipeline.py", line 7, in <module>
    outcfg = execute(**config)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/utils/pipeline.py", line 176, in execute
    outcfg = runner(**incfg)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 712, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 355, in standard
    residues = secondary_structure(**kwargs)
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/fold/protocol.py", line 117, in secondary_structure
    target_seq_file, output_dir, binary=kwargs["psipred"]
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/fold/tools.py", line 233, in run_psipred
    "psipred output is invalid", ss2_file, horiz_file
  File "/home/curtisross/anaconda3/lib/python3.7/site-packages/evcouplings/utils/system.py", line 130, in verify_resources
    "{}:\n{}".format(message, ", ".join(invalid))
evcouplings.utils.system.ResourceError: psipred output is invalid:
/home/curtisross/research/cpt-aux/mu-releasin/EVcouplings/results/mu_monomer/gp22/first_run/fold/psipred/.fa.ss2, /home/curtisross/research/cpt-aux/mu-releasin/EVcouplings/results/mu_monomer/gp22/first_run/fold/psipred/.fa.horiz
```

This is occuring on multiple different runs via the monomer pipeline on different proteins. I'm curious if there's something wrong with how I am running `psipred` or if it's a different issue entirely. I would think the results that I can see would pass the `run_psipred` portion at `verify_resources`, but that seems to be what raises this error.

Let me know if you have some questions, or would like to take a peak at any of the returns for the different steps.

Thanks for your time as always!

Curtis

**Comment by thomashopf** [comment] 2020-03-27 20:28
Hi @cross12tamu,

Can you also upload the pipeline folder for one of the runs affected by this problem please?

Also, do the following two files exist and have any contents?

/home/curtisross/research/cpt-aux/mu-releasin/EVcouplings/results/mu_monomer/gp22/first_run/fold/psipred/.fa.ss2

/home/curtisross/research/cpt-aux/mu-releasin/EVcouplings/results/mu_monomer/gp22/first_run/fold/psipred/.fa.horiz

Also, what is a bit odd are the filenames... what is the prefix of your run? Normally, the filenames should be fold/psipred/<last part of prefix>.{ss2, horiz}

**Comment by cross12tamu** [comment] 2020-03-27 21:16
[Here is a link to a shared google drive](https://drive.google.com/drive/folders/1v893Nm4sRMx5OBCXbhEaUYWrd9vHCZxJ?usp=sharing), that you *should* be able to access if I did the sharing correctly.

> Also, do the following two files exist and have any contents?
No, the only hidden file is a .ss file (which is empty)

Here's an image of my directory:
![fold_dir](https://user-images.githubusercontent.com/26947059/77801163-4b34e200-7046-11ea-8895-79b68a8268e4.png)

**Comment by cross12tamu** [comment] 2020-03-27 21:38
I have a feeling TAMU is being fussy with the sharing...

give me a second to port this to my personal gmail

**Comment by thomashopf** [comment] 2020-03-28 09:25
Okay so it looks like the PSI-BLAST step of PSIPRED works (i.e. generating the sequence alignment), but then it doesn't make any predictions. Do you get any sort of error message from PSIPRED printed to terminal?

1) Can you please try to adjust your prefix from "../results/mu_monomer/gp22/first_run/" to so:
     * it does not contain a relative path (../)
     * it does have an actual filename prefix after the last folder component (e.g. results/mu_monomer/gp22/first_run, so filenames start with "first_run" rather than being empty)
Maybe this is something that PSIPRED cannot handle as an input.

2) Are you running PSIPRED 4.0 or the older 3.x series? If 4.0, can you please see if using 3.x fixes the issue? (available here: http://bioinfadmin.cs.ucl.ac.uk/downloads/psipred/old_versions/)

**Comment by cross12tamu** [comment] 2020-03-29 00:18
I did both (1) and (2) with the same error being raised. I ended up using psipred3.5 instead of 4 for (2). 

Let me know if you need something else from me that can help debug.

Thanks for your time @thomashopf

**Comment by thomashopf** [comment] 2020-03-29 17:07
Okay, thanks a lot for trying all these things! I renamed this issue as a reminder to make the package compatible with PSIPRED v4

**Comment by cross12tamu** [comment] 2020-03-29 18:17
Do you have any recomendation for me to try and fix this? Since 3.5 and 4 didn't work, I don't know if I should use an earlier version than 3.5?

Just let me know and thanks again.

**Comment by thomashopf** [comment] 2020-03-29 18:42
Oh sorry - I had misread your answer that PSIPRED 3.5 worked.

Can you please try and see what happens if you directly run PSIPRED as a standalone tool outside the pipeline/package? Maybe this is some sort of an installation issue - or did you already have jobs where it successfully predicted secondary structure?

**Comment by cross12tamu** [comment] 2020-03-29 21:06
I ran each version of psipred outside of EVcouplings before initiating the full pipeline. I had the longest time debugging my own errors of getting the databases to sync / work. *I THINK* I have done that correctly, but perhaps not.

What is the expected output (the files/etc) of a successful PSIPRED run? I presume it's the `.ss` and `.ss2` files, as well as a `.horiz` file? If so, they're popping up when I run this (i'll attach a screenshot right after I post this)

However, those results are not popping up in the output. The temp files (like the `.blast` are there, but the PSIPRED `cleaning up...` and `Final output...` stage (maybe?) doesn't happen, since those files are not in the fold directory.

Curious...

**Comment by cross12tamu** [comment] 2020-03-30 19:59
I've reinstalled EVcouplings, as well as tried to feed the results from PSIPRED (shown above) into the fold folder to see if it would get picked up if I ran the FOLD step. It did not. 

Trying some more digging through y'alls module now to see if I can gain any insight on this error.

**Comment by cross12tamu** [comment] 2020-03-30 21:12
OH! It did catch the separate psipred files when I fed it (I believe that this is good news). 

Evidently I did something wrong with CNS. Now for me to fix that, I will look into addressing the aforementioned issue for PSIPRED (if you don't get to it first).

**Comment by cross12tamu** [comment] 2020-03-30 22:14
Just to clarify/summarize my confusing post above:

- psipred v3.5 and psipred v4 outputs are not picked up in the EVcouplings fold/psipred directory
- I ran psipred indepently, renamed the files, and put the results in the fold/psipred directory
- reran EVcouplings pipeline, no errors raised, with (seemingly) expected outputs

Somehow, it seems that psipred does not finish, and make the `.ss2` and `horiz` files, that `run_psipred` expects to see.

**Comment by thomashopf** [comment] 2020-04-03 13:03
Hmmm to me this sounds like some sort of path issue... will try to follow up soon, can you send us your modified run_psipred script?

**Comment by cross12tamu** [comment] 2020-04-03 15:40
``` bash
# psipred - PSIPRED V4 program
# psipass2 - PSIPRED V4 program
# chkparse - PSIPRED V4 program

# NOTE: Experimental PSIPRED script with BLAST+ compatability (DTJ May 2010)

# The name of the BLAST+ data bank
# set dbname = /media/curtisross/wd_hdd/databases
set dbname = /home/curtisross/research/ext-tools/BLAST-dbase/uniref100/DB

# Where the NCBI BLAST+ programs have been installed
set ncbidir = /home/curtisross/research/ext-tools/ncbi/blast+/ncbi-blast-2.9.0+/bin

# Where the PSIPRED V3 programs have been installed
set execdir = ../bin

# Where the PSIPRED V3 data files have been installed
set datadir = ../data

set basename = $1:r
set rootname = $basename:t

# Generate a "unique" temporary filename root
set hostid = `hostid`
set tmproot = psitmp$$$hostid

\cp -f $1 $tmproot.fasta

echo "Running PSI-BLAST with sequence" $1 "..."

$ncbidir/psiblast -db $dbname -query $tmproot.fasta -inclusion_ethresh 0.001 -out_pssm $tmproot.chk -num_iterations 3 -num_alignments 0 -num_descriptions 5000 >& $tmproot.blast

if ($status != 0) then
    tail $tmproot.blast
    echo "FATAL: Error whilst running blastpgp - script terminated!"
    exit $status
endif

echo "Predicting secondary structure..."

$execdir/chkparse $tmproot.chk > $tmproot.mtx

if ($status != 0) then
    echo "FATAL: Error whilst running chkparse - script terminated!"
    exit $status
endif

echo Pass1 ...

$execdir/psipred $tmproot.mtx $datadir/weights.dat $datadir/weights.dat2 $datadir/weights.dat3 > $rootname.ss

if ($status != 0) then
    echo "FATAL: Error whilst running psipred - script terminated!"
    exit $status
endif

echo Pass2 ...

$execdir/psipass2 $datadir/weights_p2.dat 1 1.0 1.0 $rootname.ss2 $rootname.ss > $rootname.horiz

if ($status != 0) then
    echo "FATAL: Error whilst running psipass2 - script terminated!"
    exit $status
endif

# Remove temporary files

echo Cleaning up ...
\rm -f $tmproot.* error.log

echo "Final output files:" $rootname.ss2 $rootname.horiz
echo "Finished."
```

**Comment by thomashopf** [comment] 2020-04-03 16:16
Thanks @cross12tamu - I have a suspicion the problem is due to the relative paths for execdir and datadir:
```
set execdir = ./bin
set datadir = ./data
```

What happens if you change these to absolute paths like for dbname and ncbidir? On the HMS compute cluster, we have both of these set as absolute paths.

**Comment by cross12tamu** [comment] 2020-04-03 16:20
I'll give that a whirl @thomashopf . Thanks as always for the response.

I will get back to you.

**Comment by cross12tamu** [comment] 2020-04-04 15:19
absolute path fixed this issue.

**Comment by thomashopf** [comment] 2020-04-08 19:19
Ok great - closing this then.

**Closed by thomashopf** 2020-04-08 19:19 UTC
